#include <Arduino.h>
#include "gif_frames.h"

const char* const gifFrames[] = {
    "/gif_data/gif_f0.bin",
    "/gif_data/gif_f1.bin",
    "/gif_data/gif_f2.bin",
    "/gif_data/gif_f3.bin",
    "/gif_data/gif_f4.bin",
    "/gif_data/gif_f5.bin",
    "/gif_data/gif_f6.bin",
    "/gif_data/gif_f7.bin",
    "/gif_data/gif_f8.bin",
    "/gif_data/gif_f9.bin",
    "/gif_data/gif_f10.bin",
    "/gif_data/gif_f11.bin",
    "/gif_data/gif_f12.bin",
    "/gif_data/gif_f13.bin",
    "/gif_data/gif_f14.bin",
    "/gif_data/gif_f15.bin",
    "/gif_data/gif_f16.bin",
    "/gif_data/gif_f17.bin",
    "/gif_data/gif_f18.bin",
    "/gif_data/gif_f19.bin",
    "/gif_data/gif_f20.bin",
    "/gif_data/gif_f21.bin",
    "/gif_data/gif_f22.bin",
    "/gif_data/gif_f23.bin",
    "/gif_data/gif_f24.bin",
    "/gif_data/gif_f25.bin",
    "/gif_data/gif_f26.bin",
    "/gif_data/gif_f27.bin",
    "/gif_data/gif_f28.bin",
    "/gif_data/gif_f29.bin",
    "/gif_data/gif_f30.bin",
    "/gif_data/gif_f31.bin",
    "/gif_data/gif_f32.bin",
    "/gif_data/gif_f33.bin",
    "/gif_data/gif_f34.bin",
    "/gif_data/gif_f35.bin",
    "/gif_data/gif_f36.bin",
    "/gif_data/gif_f37.bin",
    "/gif_data/gif_f38.bin",
    "/gif_data/gif_f39.bin",
    "/gif_data/gif_f40.bin",
    "/gif_data/gif_f41.bin",
};